language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install mock nose coverage codacy-coverage

script:
  - nosetests --with-coverage --cover-erase --cover-package=mod_amity
  - coverage xml

after_success:
  - python-codacy-coverage -r coverage.xml

cache: pip

notifications:
  email: false